nameOverride: ""
fullnameOverride: ""

appTypesImage:
  repository: "ghcr.io/neuro-inc/post-deployment-app-hook"
  tag: "development"
  pullPolicy: "Always"

postProcessorEnvs: []

enableEgressToKubeAPI: true
kubeApiIP: "10.0.0.2"
